/**
 * Script: generate-banners.js
 * Automatically scans assets/banner/ for valid image files and produces:
 *  - assets/banner/banners.json
 *  - assets/banner/banners.js
 *
 * Deterministic alphabetical ordering allows controlling slide order via filename.
 */

const fs = require('fs');
const path = require('path');

const BANNER_DIR = path.resolve(__dirname, '..', 'assets', 'banner');
const JSON_OUT = path.join(BANNER_DIR, 'banners.json');
const JS_OUT = path.join(BANNER_DIR, 'banners.js');

const VALID_EXTENSIONS = new Set(['.jpg', '.jpeg', '.png', '.webp']);

function deriveCharacterKey(filename) {
  const lower = filename.toLowerCase();
  if (lower.includes('banner-csa-books-4-kids')) return 'banner';
  if (lower.includes('benny')) return 'benny';
  if (lower.includes('bruno')) return 'bruno';
  if (lower.includes('leo')) return 'leo';
  if (lower.includes('nina')) return 'nina';
  if (lower.includes('rino')) return 'rino';
  if (lower.includes('rudy')) return 'rudy';
  return 'generic';
}

function deriveFriendlyTitle(filename) {
  const withoutExt = filename.replace(/\.[^/.]+$/, '');
  const cleaned = withoutExt.replace(/[._-]+/g, ' ').replace(/\s+/g, ' ').trim();
  return cleaned
    .split(' ')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

function generateBanners() {
  if (!fs.existsSync(BANNER_DIR)) {
    console.error(`Error: Banner directory not found: ${BANNER_DIR}`);
    process.exit(1);
  }

  const entries = fs.readdirSync(BANNER_DIR, { withFileTypes: true });

  const imageFiles = entries
    .filter(entry => {
      if (!entry.isFile()) return false;
      const ext = path.extname(entry.name).toLowerCase();
      return VALID_EXTENSIONS.has(ext);
    })
    .map(entry => entry.name);

  // Deterministic natural case-insensitive alphabetical sort
  imageFiles.sort((a, b) => a.localeCompare(b, undefined, { numeric: true, sensitivity: 'base' }));

  const manifest = imageFiles.map(file => {
    return {
      file,
      src: `assets/banner/${file}`,
      characterKey: deriveCharacterKey(file),
      title: deriveFriendlyTitle(file)
    };
  });

  // Write banners.json
  fs.writeFileSync(JSON_OUT, JSON.stringify(manifest, null, 2), 'utf-8');

  // Write banners.js
  const jsContent = `/**
 * Auto-generated by scripts/generate-banners.js
 * Generated at: ${new Date().toISOString()}
 * Do NOT edit manually. Add or remove images in assets/banner/ instead.
 */
window.BANNER_MANIFEST = ${JSON.stringify(manifest, null, 2)};
`;
  fs.writeFileSync(JS_OUT, jsContent, 'utf-8');

  console.log(`[generate-banners] Successfully processed ${manifest.length} banner images:`);
  manifest.forEach((item, index) => {
    console.log(`  ${index + 1}. ${item.file} (key: ${item.characterKey})`);
  });
  console.log(`[generate-banners] Saved:`);
  console.log(`  -> ${JSON_OUT}`);
  console.log(`  -> ${JS_OUT}`);
  return manifest;
}

module.exports = { generateBanners };

if (require.main === module) {
  generateBanners();
}
